name: CI

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 'your name'
        required: true
        default: 'uthman'
      leader_name:
        description: 'your leader name'
        required: true
        default: 'temi'
      another_name:
        description: 'another name'
        required: true
        default: 'nurudeen'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make deploy.sh executable
        run: chmod +x deploy.sh

      - name: Run deployment script
        run: ./deploy.sh

